#include	<stdio.h>
#include 	<string.h>
#include 	<time.h>
#include 	<sys/types.h>
#include	<rpc/rpc.h>	/* standard RPC include file */
#include	"date.h"	/* this file is generated by rpcgen */

#define MAX_LEN 100
CLIENT *setup(char *host);
long get_response(void);
void date(CLIENT *cl, long *option);
void cpu(CLIENT *cl);
void memory(CLIENT *cl);
void process(CLIENT *cl);


long get_response()
{
    long choice;

    printf("===========================================\n");
    printf("                   Menu: \n");
    printf("-------------------------------------------\n");
    printf("                1. Date\n");
    printf("                2. Time\n");
    printf("                3. Both\n");
    printf("                4. CPU usage\n");    
    printf("                5. Memory Usage\n");
    printf("                6. Load procs per min\n");
    printf("                7. Quit\n");
    printf("-------------------------------------------\n");
    printf("               Choice (1-7):");
    scanf("%ld",&choice);
    printf("===========================================\n");
    return(choice);
}

main(int argc, char **argv)
{
    CLIENT  *cl;        /* RPC handle */
    char    *server;
    char    **sresult;  /* return value from date_1()      */
    char    s[MAX_LEN];    /* character array to hold output */
    long    response;  /* user response                           */
    long    *lresult;    /* pointer to user response          */

    if (argc != 2) {
        fprintf(stderr, "usage: %s hostname\n", argv[0]);
        exit(1);
    }
    server = argv[1];
    lresult = (&response);
    /*
     * Create the client "handle."
     */
    if ( (cl = clnt_create(server, DATE_PROG, DATE_VERS, "udp")) == NULL) {
        clnt_pcreateerror(server);
        exit(2);
    }
    response = get_response();
    while(response != 7) {
        switch(response) {
          case 1: case 2: case 3:
            date(cl, &response);
          break;
          case 4:
            cpu(cl);
          break;

          case 5:
            memory(cl);
          break;

          case 6:
            process(cl);
          break;

        }
	response = get_response();
    }
    clnt_destroy(cl);		/* done with the handle */
    exit(0);
}

CLIENT *setup(char *server)
{
  CLIENT *cl = clnt_create(server,DATE_PROG,DATE_VERS,"udp");
  if(cl == NULL)
  {
    clnt_pcreateerror(server);
    return(0);
  }
  return(cl);
}

void cpu(CLIENT *cl)
{
  double* sresult;
  if ((sresult = cpu_1(NULL,cl)) == NULL) 
    return;
  printf("CPU usage : %lf %% \n\n",*sresult);
}

void memory(CLIENT *cl)
{
  double* sresult;
  if ((sresult = memory_1(NULL,cl)) == NULL) 
    return;
  printf("RAM usage: %lf %% \n\n",*sresult);
}

void process(CLIENT *cl)
{
  double* sresult;
  if ((sresult = process_1(NULL,cl)) == NULL) 
    return;
  int result = (int)*sresult;
  printf("Load average per min: %d\n\n",result);
}

void date(CLIENT *cl, long *option)
{
  char** sresult;
  if ((sresult = date_1(option, cl)) == NULL) 
    return;
  printf("%s\n\n",*sresult);
}


